drashland/website

docs/src/vue/components/pages/api_reference.vue

@ebebbington found a bug when clicking API RESOURCES on sidebar

Fix api_resources.vue

---

docs/src/vue/components/sidebar.vue

API_RESOURCES page should not actually be a a page. Target it to another page.

Change href

---

.github/pull_request_template.md

Added a pull request template file

[add-pr-template] Added pull request template

---

index.html

add deno-drash-middleware to the list of modules

---

rhum/vue/pages/getting_started.vue

add --allow-env flag

---

rhum/index.template.html

https://drash.land/rhum/staging

add --allow-env flag to quickstart

---

configs.ci.json
configs.json.sample
drash/vue/pages/introduction.vue

https://drash.land/drash/staging

use v1.x branch for drash import statements

---

drash/vue/pages/tutorials/requests/handling_path_params.vue

* Add documentation on optional path parameters.
**Other Notes**
* **DO NOT MERGE INTO PRODUCTION** until v1.2.0 for Drash has been released
* Here is how the docs look now:

Optional path params docs

---

rhum/vue/app.vue
rhum/vue/pages/tutorials/mocks.vue
rhum/vue/pages/tutorials/stubs.vue

* Add documentation on stubs and mocks.
**Other Notes**
* **DO NOT MERGE INTO PRODUCTION** until v1.1.0 for Rhum has been released

Rhum stubs mocks

---

assets/common/vue/code_block_import.vue
drash/vue/pages/introduction.vue

* removes the statement about using a branch name in the import statement

no more branch names allowed

---

dmm/vue/pages/getting_started.vue

Relies on, and addresses doc changes for https://github.com/drashland/dmm/pull/53
* Update docs to use more restrictive permissions

[update-dmm-docs] Add docs on permission restrictions

---

drash/vue/app.vue
drash/vue/pages/introduction.vue
drash/vue/sidebar.vue
rhum/vue/app.vue
rhum/vue/pages/getting_started.vue

Add article sections for drash and rhum

---

assets/common/vue/a_get_started.vue
assets/common/vue/breadcrumbs.vue

Cleans up some code and changes the colours of the a get started component to be like the breadcrumbs

Issue #197 improve breadcrumbs

---

sockets/vue/pages/tutorials/creating_a_server.vue

Fixes #195 
* documents small usage of tls, as someone didn't know how to

docs: Document usage of running a socket server with ssl

---

sockets/vue/app.vue
sockets/vue/pages/getting_started.vue

Fixes #167 
* Adds a feature section for sockets

chore: Add features section to sockets docs

---

index.html

Implements #215 
* Consumes the dev.to API.
* Displays latest news on the landing page. Each article is a link to the dev.to article.
* Displays "View all articles" button that navigate user to dev.to
The reason why the git diff is big is because I wrapped the content in a `<div id="app">` element -- allowing for Vue 3 to be used.

show latest news

---

sockets/vue/app.vue
sockets/vue/pages/tutorials/sending_to_specific_clients.vue

Fixes #222 
* Add docs for sending to specific clients

docs: Added documentation in Sockets for sending to a specific client

---

drash/vue/pages/tutorials/cli/create_app.vue
drash/vue/pages/tutorials/cli/introduction.vue

PR #224 edits

---

.github/workflows/production.yml

*Prod ci was trying to copy a config file that didnt exist (which is ok, just the ci didn't reflect this expected change)

Update production ci following configs change

---

assets/common/vue/sidebar.vue
configs.json
dmm/vue/app.vue
dmm/vue/pages/cli_commands/check.vue
dmm/vue/pages/cli_commands/help.vue
dmm/vue/pages/cli_commands/info.vue
dmm/vue/pages/cli_commands/update.vue
dmm/vue/pages/cli_commands/version.vue
dmm/vue/pages/getting_started.vue
webpack.config.js

Includes #209 (update docs to reflect release v1.2.0)
Includes #235 (add latest news to sidebar)
Includes #240 (add youtube badge)

docs: dmm v1.2.0 docs

---

drash/example_code/tutorials/servers/serving_virtual_paths/back_end/app.ts
drash/example_code/tutorials/servers/serving_virtual_paths/back_end/home_resource.ts
drash/example_code/tutorials/servers/serving_virtual_paths/folder_structure.txt
drash/example_code/tutorials/servers/serving_virtual_paths/front_end/style.css
drash/vue/app.vue
drash/vue/pages/tutorials/servers/serving_virtual_paths.vue

Addresses #247 
* Completes drashland/deno-drash#169 (virtual paths documentation requirement)

docs: Virtual Paths

---

rhum/vue/app.vue

Fixes #234 
* Add latest news to sidebar, copied impl from dmm

docs: Add latest news to rhum sidebar

---

assets/common/vue/app_root.vue
dmm/vue/app.vue
drash/vue/app.vue
rhum/vue/app.vue

* DRYs code when populating Latest News section in sidebars for each website

chore: Unify latest news section in sidebar

---

drash/assets/js/_app.js
drash/assets/js/_example_code.js

Fix staging

---

sockets/vue/pages/advanced_tutorials/creating_a_chat_app/part_2.vue
sockets/vue/pages/tutorials/adding_clients_to_channels.vue
sockets/vue/pages/tutorials/closing_channels.vue
sockets/vue/pages/tutorials/opening_channels.vue
sockets/vue/pages/tutorials/removing_clients_from_channels.vue
sockets/vue/pages/tutorials/sending_to_specific_clients.vue

Fixes #226 
* Remove openChannel() from everywhere, and where required, replace with an on() to make sure the docs are still valid

docs: Remove all instances of openChannel and replace them with on() where needed

---

configs.json

This was auto-generated by GitHub Actions.

chore: Update dependencies

---

assets/common/vue/sidebar.vue

Fixes #275 
* Checked across repos and sidebar works as expected.
Picture:

chore: Make sidebar collapsable

---

dmm/vue/pages/cli_commands/help.vue
dmm/vue/pages/getting_started.vue

fixes #276 
* Document usages of new perms

docs: Document new permissions for using dmm

---

configs.json

This was auto-generated by GitHub Actions.

chore: Make necessary pre-release changes

---

assets/common/vue/app_root.vue
assets/common/vue/introduction_header.vue
assets/common/vue/sidebar.vue
configs.js
src/modules/dmm/vue/app.vue
src/modules/drash/vue/app.vue
src/modules/rhum/vue/app.vue
src/modules/wocket/vue/app.vue
webpack.config.js
webpack.config.version.js

* Adds a dropdown to the sidebar
* Makes the copyright year configurable through server configs

feat: version selector dropdown menu

---

.github/workflows/pre_release.yml
README.md
configs.js

*Imagine this pr was triggered by creating a `release-v0.6.2` branch for wocket*

Update wocket to v0.6.2

---

console/compile_vue_routes.js
src/wocket/vue/app.vue
src/wocket/vue/pages/tutorials/reserved_event_names.vue

Addresses part of #213 
Adds reserved event names docs

docs(wocket): Add reserved event names page

---

src/drash/vue/pages/tutorials/requests/handling_path_params.vue

Address #335 
Super complex changes

Typo on drash path params tutorial

---

.github/workflows/project_issue_automation.yml
.github/workflows/project_pull_request_automation.yml

I noticed website PR's and issues weren't being tracked into the Omnipresent project

chore: Add project workflows

---

configs.js
console/bumper.ts
console/update_module_versions.js

* Bumper script was failing in the CI (see castle actions)
* This fixes it, i ran it myself and everything works
* As i ran it,  it also updates the configs so i thought i may as well commit them

[fix-bumper] Fix bumper script failing when ran in the ci

---

src/drash/vue/pages/advanced_tutorials/creating_an_api/part_3.vue
src/drash/vue/pages/advanced_tutorials/creating_an_api/part_4.vue

docs(drash): Fix creating an api typos and build issues

---

src/drash/vue/app.vue
src/drash/vue/pages/tutorials/requests/handling_forms_and_file_uploads.vue

Fixes #323 
* New tutorial on how to handle forms and file uploads with a web based example

docs(drash): Add tutorial on submitting forms and files

---

assets/common/vue/sidebar.vue
src/drash/vue/app.vue
src/drash/vue/description.vue

Address #331 
* Adds link to repo in sidebar (making it quite visible)
* mentions it in introduction

docs(drash): mention middleware

---

deps.ts

Referencing the lastest Drash version to prevent LoggerService error.

fix: Update drash version in deps.ts

---

configs.js
console/webpack_development.ts
console/webpack_production.ts

fix: Address issues with building; remove wocket v1 refs as it isn't released

---

.github/workflows/master.yml
README.md
configs.js
console/compile_drash_v1.x_api_reference
ecosystem.config.sample.js
package.json
tests/integration/module_resource_test.ts

Note that this. PR:
1. Removes `~/.local/bin` from the npm scriptss

chore: Fix master workflow

---

src/views/landing.html

Huge changes, needs everyone to review
Addresses #328

fix(landing): Fix typo for meta viewport in landing.html

---

src/modules/wocket-v0.x/vue/pages/advanced_tutorials/creating_a_chat_app/introduction.vue
src/modules/wocket-v0.x/vue/pages/advanced_tutorials/creating_a_chat_app/part_1.vue
src/modules/wocket-v0.x/vue/pages/advanced_tutorials/creating_a_chat_app/part_2.vue
src/modules/wocket-v0.x/vue/pages/advanced_tutorials/creating_a_chat_app/part_3.vue

fix(wocket): Fix navigation in chat app advanced tutorial

---

src/modules/drash-v1.x/vue/app.vue
src/modules/drash-v1.x/vue/pages/introduction.vue

docs(drash): Add section on using a Drash badge

---

src/modules/drash-v1.x/vue/pages/introduction.vue
src/resources/base_resource.ts
src/resources/landing_resource.ts
src/resources/module_resource.ts

Instead of logging to the console, let's write logs so that we can look through them to see what resources are being requested and how many times they're being requested.

feat: write logs

---

src/modules/drash-v1.x/vue/pages/introduction.vue
src/views/landing.html

Addresses #373 
Needs to be checked on staging if links do display correctly

chore: Add content for og tags

---

assets/common/vue/code_block.vue

fix: Highlighted code not aligned for safari

---

src/modules/sinco-v1.x/vue/pages/tutorials/clicking_elements.vue
src/modules/sinco-v1.x/vue/pages/tutorials/custom_assertions.vue
src/modules/sinco-v1.x/vue/pages/tutorials/evaluate_page.vue
src/modules/sinco-v1.x/vue/pages/tutorials/get_and_set_input_value.vue
src/modules/sinco-v1.x/vue/pages/tutorials/using_within_docker.vue
src/modules/sinco-v1.x/vue/pages/tutorials/visit_pages.vue
src/modules/sinco-v1.x/vue/pages/tutorials/waiting.vue
src/modules/sinco-v2.x/vue/pages/tutorials/clicking_elements.vue
src/modules/sinco-v2.x/vue/pages/tutorials/creating_a_client.vue
src/modules/sinco-v2.x/vue/pages/tutorials/custom_assertions.vue
src/modules/sinco-v2.x/vue/pages/tutorials/evaluate_page.vue
src/modules/sinco-v2.x/vue/pages/tutorials/get_and_set_input_value.vue
src/modules/sinco-v2.x/vue/pages/tutorials/using_within_docker.vue
src/modules/sinco-v2.x/vue/pages/tutorials/visit_pages.vue
src/modules/sinco-v2.x/vue/pages/tutorials/waiting.vue

Fixes #400 
* Added the documentation comments and example to demonstrate the features
* Also mended a minor grammar issue I found.
Write other useful information about this pull request here

400 documentation for sinco issue 61

---

src/modules/sinco-v2.x/vue/pages/tutorials/evaluate_page.vue

fix(sinco): sinco v2 evaluate docs fail

---

.github/workflows/master.yml
console/update_module_versions.js
src/modules/sinco-v2.x/vue/pages/tutorials/evaluate_page.vue

Fix update modules script

---

src/modules/dmm-v1.x/vue/pages/cli_commands/check.vue
src/modules/dmm-v1.x/vue/pages/cli_commands/update.vue
src/modules/dmm-v1.x/vue/pages/getting_started.vue
src/modules/dmm-v1.x/vue/pages/tutorials/automate_updating_dependencies.vue
src/modules/drash-v1.x/vue/pages/advanced_tutorials/creating_a_react_app/deno_tweets/part_1.vue
src/modules/drash-v1.x/vue/pages/advanced_tutorials/creating_a_react_app/deno_tweets/part_2.vue
src/modules/drash-v1.x/vue/pages/advanced_tutorials/creating_a_react_app/deno_tweets/part_4.vue
src/modules/drash-v1.x/vue/pages/advanced_tutorials/creating_a_server_side_rendered_app/part_1.vue
src/modules/drash-v1.x/vue/pages/advanced_tutorials/creating_a_server_side_rendered_app/part_2.vue
src/modules/drash-v1.x/vue/pages/advanced_tutorials/creating_a_vue_app/deno_tweets/part_1.vue
src/modules/drash-v1.x/vue/pages/advanced_tutorials/creating_a_vue_app/deno_tweets/part_2.vue
src/modules/drash-v1.x/vue/pages/advanced_tutorials/creating_an_api/part_1.vue
src/modules/drash-v1.x/vue/pages/advanced_tutorials/creating_an_api/part_2.vue
src/modules/drash-v1.x/vue/pages/advanced_tutorials/creating_an_api/part_3.vue
src/modules/drash-v1.x/vue/pages/advanced_tutorials/creating_an_api/part_4.vue
src/modules/drash-v1.x/vue/pages/introduction.vue
src/modules/line-v0.x/vue/pages/getting_started.vue
src/modules/rhum-v1.x/vue/pages/getting_started.vue
src/modules/sinco-v1.x/vue/pages/getting_started.vue
src/modules/sinco-v1.x/vue/pages/tutorials/evaluate_page.vue
src/modules/sinco-v2.x/vue/pages/getting_started.vue
src/modules/sinco-v2.x/vue/pages/tutorials/evaluate_page.vue
src/modules/wocket-v0.x/vue/pages/getting_started.vue

chore: Ensure all code block titles have prefix

---

src/modules/sinco-v2.x/vue/pages/tutorials/custom_assertions.vue

Why? see https://github.com/drashland/sinco/pull/66

docs(sinco): Update custom assertions docs following changes to chromstatus.com

---

src/modules/drash-v1.x/vue/pages/tutorials/resources/creating_a_resource.vue

[#438] fix spelling in resource tutorial

---

src/modules/sinco-v2.x/vue/pages/tutorials/creating_a_client.vue

chore(docs/sinco): Add note about windows TMPTDIR path in tutorial

---

src/modules/dmm-v1.x/vue/pages/cli_commands/update.vue
src/modules/drash-v1.x/vue/pages/advanced_tutorials/creating_an_api/part_2.vue

Adds docs for https://github.com/drashland/dmm/pull/114

docs(dmm): Add docs for issue #36 dmm

---

src/modules/drash-v1.x/vue/pages/advanced_tutorials/using_drash_with_docker_compose/part_1.vue

fix(drash): Creating A Server link didnt redirect to the appropriate doc page

---

src/modules/drash-v1.x/vue/pages/tutorials/requests/handling_forms_and_file_uploads.vue

docs for https://github.com/drashland/deno-drash/pull/526

docs(drash): document request.getBodyFiles() method
